import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./landing/Navbar";
import ThemeWrapper from "./landing/ThemeWrapper";
import SocketProvider from "@/context/SocketProvider";
import Footer from "./landing/Footer";
import ScrollToTop from "./common/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050505] selection:bg-neon-green selection:text-neon-green   `}
      >
        <SocketProvider>
          <Navbar />
          <ThemeWrapper>{children}</ThemeWrapper>
          <ScrollToTop />
        </SocketProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
